name: Build and Test Java
on:
  pull_request:
    paths:
      - payjoin-ffi/**
      - .github/workflows/java.yml

jobs:
  build-java-and-test:
    name: "Build and test java"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-26.04, macos-latest]
    env:
      RUSTUP_TOOLCHAIN: 1.85.0
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: "Install Rust 1.85.0"
        uses: dtolnay/rust-toolchain@1.85.0
      - name: "Use cache"
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: msrv-workspace
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "22"
      - name: Install uniffi-bindgen-java
        run: |
          cargo install uniffi-bindgen-java \
            --git https://github.com/ram0verflow/uniffi-bindgen-java \
            --branch backport-0.4.2-error-templates
      - name: Generate and test
        working-directory: payjoin-ffi/java
        run: bash ./contrib/test.sh

  compile-java-without-test-utils:
    name: "Compile Java without _test-utils"
    runs-on: ubuntu-26.04
    env:
      RUSTUP_TOOLCHAIN: 1.85.0
      PAYJOIN_FFI_FEATURES: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: "Install Rust 1.85.0"
        uses: dtolnay/rust-toolchain@1.85.0
      - name: "Use cache"
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: msrv-workspace
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "22"
      - name: Install uniffi-bindgen-java
        run: |
          cargo install uniffi-bindgen-java \
            --git https://github.com/ram0verflow/uniffi-bindgen-java \
            --branch backport-0.4.2-error-templates
      - name: Generate production API and compile
        working-directory: payjoin-ffi/java
        run: |
          bash ./scripts/generate_bindings.sh
          ./gradlew --no-daemon compileJava
